### ISSUE TITLE
Evaluation Platform

### ISSUE THREAD

**Issue by abukharmeh** [CTSRD-CHERI/Piccolo#15]
Hi, 

I am starting to evaluate CHERI Piccolo Implementation and I am wondering if there is a stable branch, commit or tag I should base my evaluation on. 

Kind regards,
Ibrahim

**Comment by PeterRugg** [comment]
Apologies for the delay on this! We're in the middle of doing some evaluation of our own. The ECATS-final-baseline and ECATS-final-CHERI are the branches we're using for non-CHERI and CHERI respectively, and will likely be suitable for other evaluation.

**Comment by abukharmeh** [comment]
Yes likely they are, I will start looking at them,  thank you very much .

**Comment by jrtc27** [comment]
Do note though that:

* Piccolo is not a great design for a microcontroller, it was created as a squashed-down version of the 5-stage Flute rather than being designed from the ground up to be an efficient microcontroller
* We have not spent a huge amount of time optimising CHERI-Piccolo's area overhead compared with Piccolo beyond what we're obliged to do as part of the DARPA SSITH program

so take any conclusions about the impact on hardware design with a large amount of salt
